"""empty message

Revision ID: 44ac6b7eca7f
Revises: f1fbc70fc6f1
Create Date: 2021-09-01 16:57:16.663469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ac6b7eca7f'
down_revision = 'f1fbc70fc6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.add_column('auctions', sa.Column('city', sa.String(), nullable=False))
    op.add_column('auctions', sa.Column('state', sa.String(), nullable=False))
    op.add_column('auctions', sa.Column('miles', sa.Integer(), nullable=False))
    op.add_column('auctions', sa.Column('color', sa.String(), nullable=False))
    op.add_column('auctions', sa.Column('engine', sa.String(), nullable=False))
    op.add_column('auctions', sa.Column('transmission', sa.String(), nullable=False))
    op.add_column('auctions', sa.Column('img_url_1', sa.Text(), nullable=False))
    op.add_column('auctions', sa.Column('img_url_2', sa.Text(), nullable=False))
    op.add_column('auctions', sa.Column('img_url_3', sa.Text(), nullable=False))
    op.add_column('auctions', sa.Column('img_url_4', sa.Text(), nullable=False))
    op.drop_column('auctions', 'reserve_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('reserve_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('auctions', 'img_url_4')
    op.drop_column('auctions', 'img_url_3')
    op.drop_column('auctions', 'img_url_2')
    op.drop_column('auctions', 'img_url_1')
    op.drop_column('auctions', 'transmission')
    op.drop_column('auctions', 'engine')
    op.drop_column('auctions', 'color')
    op.drop_column('auctions', 'miles')
    op.drop_column('auctions', 'state')
    op.drop_column('auctions', 'city')
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name='images_auction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    # ### end Alembic commands ###
